version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_USER=sa
      - DB_PASSWORD=@Qweasd78912345
      - DB_HOST=localhost  
      - DB_NAME=RecipeSharing
